### ISSUE TITLE
query parameter encoding

### ISSUE THREAD

**Issue by arundhaj** [fabiomaffioletti/jsondoc#108]
query parameters are not encoded while making ajax request.

**Comment by fabiomaffioletti** [comment]
Please follow the guidelines for submitting a bug. Make examples, use real values, make me understand how I can reproduce the problem.

**Comment by arundhaj** [comment]
Sorry.
I thought to fix and send a pull request, however found that it was already fixed in v1.1.12 (https://github.com/fabiomaffioletti/jsondoc/commit/f5a28025fbb6b61821d2c7c6fece6abfb1e99d60)
I was using v1.1.9, so merged that fix to my local.

Thanks for this project, it is being useful.

**Comment by fabiomaffioletti** [comment]
Ok, glad to hear that.
