### ISSUE TITLE
Dependency License

### ISSUE THREAD

**Issue by yohanakh** [fabiomaffioletti/jsondoc#116]
Reflections is one of the dependencies of JSONDoc.
The issue is that it is licensed under WTFPL license which we cannot use.
Is there a way to not use this license? Maybe replacing the library?

Thanks

**Comment by fabiomaffioletti** [comment]
That's tricky. I had in mind to remove the dependency, but it's a low priority task. By the way: isn't the WTFPL enough for you? :-)

**Comment by fabiomaffioletti** [comment]
Shall I close this?
