### ISSUE TITLE
UI : Some questions.

### ISSUE THREAD

**Issue by sadikr** [fabiomaffioletti/jsondoc#119]
1) For jsondoc-ui, why we have named html file to "jsondoc-ui"? should not it be "index.html"
Reason : I've integrated JSONDoc in one of my application, where I'm generating jsondoc-ui folder via defining dependency in pom.xml. And when I try to access the doc with url like .. 
http://localhost:8080/json-doc/ 
This url gives me nothing, I've to specify that html file to access my  app's api-doc. 

2) I've gone through the jsondoc-ui.html file, why aren't we separating the html,css,js code? 

Sorry! if this is not the place to raise such question.

**Comment by fabiomaffioletti** [comment]
Hello and thank you for your questions. Here are my answers:
1) index.html is usually a name that is used by everyone to indicate the main (or welcome, or home) page. I wanted to avoid to overlap with that concept. In your application you can always map the /json-doc path to the jsondoc-ui.html view.
2) This is a good point. Currently there are two projects: jsondoc-ui and jsondoc-ui-webjar. I wanted to consolidate them and have only one, but I did not have time to do that. In any case, as a first step, it's possible (and good) to separate css/js from the html. It's a low priority task, but I'll definitely do that soon or later ;) Opening an issue right now about that.

**Comment by sadikr** [comment]
@fabiomaffioletti  : Got the points. :+1: . Do let me know if you want help on separating css/js from html. I am ready to contribute.

**Comment by fabiomaffioletti** [comment]
Just done. Will be released in the next days.
