### ISSUE TITLE
allowedvalues ignored for APIObjectField if it's an enum type

### ISSUE THREAD

**Issue by brubin-blurb** [fabiomaffioletti/jsondoc#123]
I have an enum that I have implemented a Converter for to use a getLabel() method for conversion rather than the standard name value.  My allowedvalues values are ignored on APIObjectField and no matter what I do it simply shows the enum constants.

**Comment by fabiomaffioletti** [comment]
I see. I think the best way to proceed is to use the allowedvalues property of the ApiObjectField annotation to override the enum values. I'll implement that.
