### ISSUE TITLE
Support ApiErrors annotation at class level

### ISSUE THREAD

**Issue by mcubrilo** [fabiomaffioletti/jsondoc#125]
Rationale: Most APIs have at least a few common errors that are the same for all endpoints. E.g. (400, 403, 500) will probably mean the same for all your endpoints. In this case, class level annotation would help to avoid copying around the same error definitions to endpoints methods.

When `ApiErrors` annotation is present at the class level errors should be applied to all member methods. Member methods can override the errors declared at the class level and provide more specific ones.

**Comment by fabiomaffioletti** [comment]
Merged.
