### ISSUE TITLE
Jsondoc offline placeholder verification

### ISSUE THREAD

**Issue by yenn** [fabiomaffioletti/jsondoc#136]
GIVEN
* Using replacement of the _JSONDOC_OFFLINE_PLACEHOLDER_ by maven replacer plugin.

WHEN
* jsondoc content contains exactly 4 underscore characters

THEN
* condition if(jsondoc.split('_').length != 5) will fail and the content will not be loaded despite the fact that the placeholder has been replaced

Replacement verification condition is wrong.

**Comment by fabiomaffioletti** [comment]
Good catch, thank you!
