### ISSUE TITLE
[Request] Create Object Field Requirements from Hibernate Validation Annotations 

### ISSUE THREAD

**Issue by lukasbradley** [fabiomaffioletti/jsondoc#141]
Hibernate Validator is an extremely popular method by which request objects can be validated before processing.   http://hibernate.org/validator/

I'd recommend providing support so these annotations can become a replacement/addendum to the ApiObjectField annotation information.  As of now, I'm duplicating information as both are required.

I'd be happy to work on this functionality if you'd give me a rough outline of where to start.  I'd be MORE interested in making a monetary donation to make it happen.

Let me know your thoughts, and thank you for a great tool.

**Comment by fabiomaffioletti** [comment]
This is a very good idea. I need some time to investigate the possible solutions but it's definitely worth providing support for hibernate validator.

**Comment by fabiomaffioletti** [comment]
Hey @lukasbradley I just released the new version that integrates hibernate validator. It will be available in a few hours on maven central.

**Comment by lukasbradley** [comment]
you are a rockstar.

**Comment by fabiomaffioletti** [comment]
:smile:
