### ISSUE TITLE
Spring RequestMapping "path" variable is ignored

### ISSUE THREAD

**Issue by ST-DDT** [fabiomaffioletti/jsondoc#162]
Spring's `RequestMapping` anntoation has an alias for `value` called `path` that don't get picked up by the documentation generator.

![missingpath](https://cloud.githubusercontent.com/assets/1579362/10712631/c3dc0838-7a9f-11e5-9208-0789e59b88c8.png)

````java
@RequestMapping(path = "/register")
public String register() {
	[...]
}

@RequestMapping(path = "/register.do", method = RequestMethod.POST)
public ModelAndView register(...) {
	[...]
}
````

But it will be shown correctly if I use the `value` attribute for the mapping.

````java
@RequestMapping(value = "/register")
public String register() {
	[...]
}

@RequestMapping(value = "/register.do", method = RequestMethod.POST)
public ModelAndView register(...) {
	[...]
}
````

However I prefer using `path` as it say more about what the param is describing. This becomes more important if you have more attributes on the annotation. The `path` value is also easier to read during code reviews or when showing the code to other people that might not have that much experience with spring.

````java
@RequestMapping(path = "/version", method = RequestMethod.GET, 
		consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE, ...},
		produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE, ...},
		name="Version validation", headers="ext: *")
````

I use 
* Spring: 4.2.2.RELEASE  
````xml
<dependency>
	<groupId>org.springframework</groupId>
	<artifactId>spring-webmvc</artifactId>
	<version>4.2.2.RELEASE</version>
	<!-- The Apache Software License, Version 2.0 -->
</dependency>
````
* JsonDoc: 1.2.9  
````xml
<dependency>
	<groupId>org.jsondoc</groupId>
	<artifactId>jsondoc-springmvc</artifactId>
	<version>1.2.9</version>
	<!-- MIT License -->
</dependency>
````

PS: Thanks for your nice tool + work.

**Comment by fabiomaffioletti** [comment]
See #171
