### ISSUE TITLE
TypeVariableImpl cannot be cast to java.lang.reflect.ParameterizedType (Related to Issue # 146}

### ISSUE THREAD

**Issue by nileshagrawal02** [fabiomaffioletti/jsondoc#174]
Unable to generate the jsondoc json with latest released version 1.2.10. It happens when an object field is of collection type with generics. This seems to be related to Issue #146 but it falls on different code path.

```java
@ApiObject
public class ClassA<T> {
...
@ApiObjectField
public List<T> objects;
...
}
```
Stack Trace:
> Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.reflect.ParameterizedType
>    at org.jsondoc.springmvc.scanner.AbstractSpringJSONDocScanner.buildJSONDocObjectsCandidates(AbstractSpringJSONDocScanner.java:106)
>    at org.jsondoc.springmvc.scanner.AbstractSpringJSONDocScanner.jsondocObjects(AbstractSpringJSONDocScanner.java:161)
>    at org.jsondoc.core.scanner.AbstractJSONDocScanner.getJSONDoc(AbstractJSONDocScanner.java:96)

**Comment by pk1** [comment]
Same problem here with the latest version 1.2.14
