### ISSUE TITLE
Generate description based on method name.

### ISSUE THREAD

**Issue by magdenkov** [fabiomaffioletti/jsondoc#175]
For example given Spring mvc with spring boot
@RequestMapping(value = "/project/{id}",
            method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Project> getProjectById(@PathVariable("id") String id) { }

Than will be generated
/* Get project by id */
/project/{id} GET

So no addiitional annotations like @ApiMethod (description =" ") will be needed at all. 
Selfdocumented code)

**Comment by fabiomaffioletti** [comment]
Sounds good, but instead of putting that value in the description I added another MethodDisplay called METHOD that uses the method name instead of the URI / SUMMARY. I like the idea of a self documented approach, but I prefer to leave the description field as free as possible.
