### ISSUE TITLE
Demo Link on http://jsondoc.org/ gives Javascript error dialog

### ISSUE THREAD

**Issue by madhumm** [fabiomaffioletti/jsondoc#176]
Demo Link on http://jsondoc.org/ gives Javascript error dialog
![jsondoc](https://cloud.githubusercontent.com/assets/849798/12209219/98d62432-b61f-11e5-8e31-e3e2fcb56a53.png)

**Comment by fabiomaffioletti** [comment]
It seems that OpenShift had some problems. I restarted the application and now it should work fine. Thank you.
