### ISSUE TITLE
RepositoryRestController support

### ISSUE THREAD

**Issue by viethang** [fabiomaffioletti/jsondoc#189]
Hello,

I'm using jsondoc for my spring-data-rest-webmvc project. It works really great! Thanks for the tool.

In my project, I use Controllers, RestControllers and RepositoryControllers. It turns out that jsondoc scan only Controllers and RestControllers but not RepositoryRestControllers. 

I made it work by 
1. add spring-data-rest-webmvc package to pom.xml of jsondoc-springmvc
2. add getTypesAnnotatedWith(RepositoryRestController.class)

I think that it would be useful to support RepositoryRestController in jsondoc.
Would you like me to make a pull request for this?

**Comment by fabiomaffioletti** [comment]
Hello, yes create a PR, I'll review it as soon as I can. Thank you
