### ISSUE TITLE
Not support Spring 4.3 @Get/@PostMapping etc

### ISSUE THREAD

**Issue by clinker** [fabiomaffioletti/jsondoc#204]
Spring 4.3 comes with @GetMapping, @PostMapping, etc.
JSONDoc v2.1.5 doest not scan these annotations.

**Comment by clinker** [comment]
Same issue also found in:

- SpringVerbBuilder

- SpringQueryParamBuilder

- SpringProducesBuilder

- SpringPathBuilder

- SpringHeaderBuilder

- SpringConsumesBuilder

The reason is all of the above scan only "RequestMapping".

**Comment by clinker** [comment]
My solution: https://github.com/clinker/jsondoc.git

**Comment by linux-china** [comment]
please use AnnotatedElementUtils.isAnnotated() and  AnnotatedElementUtils.getMergedAnnotation() to replace Java reflection api

**Comment by sitthinutk** [comment]
I'd love to have this feature! I'm also struggle with unscanned annotations.

**Comment by fabiomaffioletti** [comment]
Thanks guys
