### ISSUE TITLE
Java 8 compatibility 

### ISSUE THREAD

**Issue by arbach** [fabiomaffioletti/jsondoc#216]
If I add this line 
`
list.sort(Comparator.comparing( a -> .. 
`

where list is 

`List<Object>` 

the whole controller disappears from the docs. Not sure if this is something I am doing wrong ..

**Comment by ST-DDT** [comment]
Can you create a complete class/method that showcases the issue?

**Comment by arbach** [comment]
This class will not show in the documentation.  It will show up if you comment the filter line. 


import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.security.RolesAllowed;
import org.jsondoc.core.annotation.Api;
import org.jsondoc.core.annotation.ApiAuthToken;
import org.jsondoc.core.annotation.ApiMethod;
import org.jsondoc.core.pojo.ApiStage;
import org.jsondoc.core.pojo.ApiVisibility;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

@Api(name = "/stream", description = "Stream issue demo", group = "demo", visibility = ApiVisibility.PRIVATE, stage = ApiStage.RC)
@ApiAuthToken(roles = "USER", scheme = "Bearer")
@Controller
@RequestMapping(value = "/api")
public class StreamTest  {

    @RolesAllowed({"ROLE_USER"})
    @ApiMethod(description = "demo")
    @RequestMapping(value = "/demo", method = RequestMethod.GET)
    protected @ResponseBody
    Object inputsGet() throws Exception {
        List<String>test = new ArrayList<>();
        test.add("x"); 
//       comment the following line
      test.stream().filter( i -> i == "x").collect(Collectors.toList());
        return "done";
    }

}

**Comment by fabiomaffioletti** [comment]
@arbach See https://github.com/fabiomaffioletti/jsondoc/tree/master/jsondoc-core/src/test/java/org/jsondoc/core/issues/issue216

Please reopen if you still have this issue
