### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by mathieucarbou** [fabiomaffioletti/jsondoc#222]
Hi,

We are using Spring-Boot and Json Doc in a project. Before delivery, we have to go through a license check and we found an issue in this project.

Its license is MIT, but the project is using the JLinq library in the `jsondoc-ui-webjar` module (which we are using), which as a CC license.

__First problem__ is that The CC license requires attribution (quoted): _You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use._ 

=> So there should be a place somewhere in the Json Doc project where you give credit for the use of this JS library.

__Second problem__ is that we have a policy preventing us to use this kind of CC licensing.

=> So how is this library necessary to make `jsondoc-ui-webjar` work ? Is it removable easily or it is required ? Would it be hard to remove this dependency or replace it by another one without licensing issues ?

Thanks!

**Comment by fabiomaffioletti** [comment]
Thank you very much for spotting this.

Regarding the first problem I added the attribution on the website in the Credits page.

Regarding the second one, the library is required for the correct functionality of the documentation page, so it could be hard to remove it. But you can implement your own documentation viewer using the json returned by the /jsondoc endpoint.

**Comment by fabiomaffioletti** [comment]
By the way, I just released version 1.2.17 in which I removed jLinq. Give time to maven central to synchronize (some hours) and then you can use the project with no worries.
