### ISSUE TITLE
@RequestParam(name = "param_name") ignored.

### ISSUE THREAD

**Issue by frickua** [fabiomaffioletti/jsondoc#236]
`name()` is alias for `value()` in `@RequestParam`. That mean, that we must analyze it too.

[SpringQueryParamBuilder](https://github.com/fabiomaffioletti/jsondoc/blob/master/jsondoc-springmvc/src/main/java/org/jsondoc/springmvc/scanner/builder/SpringQueryParamBuilder.java)

**Comment by fabiomaffioletti** [comment]
Solved by merging PR.
