### ISSUE TITLE
RequestParam#name() ignored

### ISSUE THREAD

**Issue by rtomsick** [fabiomaffioletti/jsondoc#239]
Description
---

It appears that JSONDoc is ignoring the `name` attribute of the `RequestParam` annotation.  The `value` attribute works as expected, despite the former being an alias for the latter.

Steps to reproduce
---

Attempt to generate documentation for a method like the following

```java

@RequestMapping(value = "")
public void
authenticate(@RequestParam("username") String username, 
				@RequestParam("password") String password, 
				@RequestParam(required = false, name = "source") 
				String source)
throws IOException {/* ... */}
```

Expected outcome
---

The three query parameters ("username", "password", "source") are present in the resulting documentation.

Actual outcome
---
"source" is not present in the resulting documentation, instead the parameter is shown with no name, and the following error is present in a notice above the parameter descriptions: "- Missing documentation data: query parameter name"

Suggested resolution
---
Treat `value` and `name` as synonyms, since that is what Spring does.

**Comment by fabiomaffioletti** [comment]
Solved with #236
