### ISSUE TITLE
Would you accept a pull request to remove the servlet-api dependency?

### ISSUE THREAD

**Issue by toranb** [fabiomaffioletti/jsondoc#46]
Today I tried to use this w/ a springboot app and ran into a ton of pain. I finally realized it wouldn't boot because of a conflict between servlet-api versions. I was using 3.1 but this app today uses 2.4

Would you accept a PR to remove this hard coded dependency so others using springboot won't feel this pain?

https://github.com/fabiomaffioletti/jsondoc/blob/master/pom.xml#L123

Thank you for maintaining such a great OSS project !

**Comment by fabiomaffioletti** [comment]
Hello, I am on it. I am also writing a jsondoc starter for spring boot which I'll push shortly. I'll release it and document how to use it soon. Anyway, glad to see that, apart from the servlet version, it's working with spring boot.
