### ISSUE TITLE
Add option "template" in ApiBodyObject

### ISSUE THREAD

**Issue by yohanakh** [fabiomaffioletti/jsondoc#69]
Add option "template" which is a class name in ApiBodyObject.
This will allow showing a template or an example for each method via the ui.

**Comment by fabiomaffioletti** [comment]
Hi @yohanakh, I think I did not understand very well. Is it something like https://github.com/fabiomaffioletti/jsondoc/issues/44?

**Comment by yohanakh** [comment]
Hi @fabiomaffioletti ,

Yes, more or less.

I want to show a json template in the Playground
