### ISSUE TITLE
BUG: Required fields are not checked in Playground

### ISSUE THREAD

**Issue by yohanakh** [fabiomaffioletti/jsondoc#70]
The Playground allows the user to submit the form even if there are required empty fields that should not be empty.

**Comment by fabiomaffioletti** [comment]
This is not a bug. This is to let api users get error responses and eventually tune their clients to properly handle them.

**Comment by yohanakh** [comment]
I think it is a bug because in my case i have two APIs like:
/{type}/ - that gets all entries of type {type}
/{type}/{id} - that gets the entry with the provided {id}

If the playground allows providing empty value for the {id} then the first API will be called - > problem!

**Comment by fabiomaffioletti** [comment]
Ok I got it. For path parameters it makes sense to do a check before submitting.Thank you.
