### ISSUE TITLE
BUG: JSONDoc cannot run with Java 6

### ISSUE THREAD

**Issue by yohanakh** [fabiomaffioletti/jsondoc#71]
I am getting the UnsupportedClassVersionError : Unsupported major.minor version 51.0
From both jsondoc-core and jsondoc-springmvc.

Is there a reason why Java 6 is not supported?

Thanks

**Comment by fabiomaffioletti** [comment]
I'll mark that as bug and evaluate if support java 6. thanks

**Comment by yohanakh** [comment]
You only need to change the source and target version to 1.6 instead of 1.7 in maven-compiler-plugin plugin

**Comment by yohanakh** [comment]
Is there a planned date for the release with the fix ?
Thanks

**Comment by fabiomaffioletti** [comment]
It's released. In a few hours it will be available on maven central.

**Comment by yohanakh** [comment]
Thanks a bunch :+1:
