### ISSUE TITLE
Support custom API response status.

### ISSUE THREAD

**Issue by dostermeier** [fabiomaffioletti/jsondoc#8]
Not all RESTful API methods return a 200 on success.  For example, it is common to return a 201 for a successful POST.  

It seems like this would be a good candidate for another annotation, although I am weary of suggesting the creation of annotations for everything :)

It would be very useful to support some indication in the UI of what the response status of an API call will be. (aside from the error response statuses).

**Comment by fabiomaffioletti** [comment]
The response status will be a new attribute of @ApiMethod annotation and will default to 200.
