### ISSUE TITLE
playground Validation errors: id must not be empty

### ISSUE THREAD

**Issue by MarcMielke** [fabiomaffioletti/jsondoc#84]
for a non required parameter:
![region capture 1](https://cloud.githubusercontent.com/assets/1066601/5874745/74815f76-a305-11e4-9f49-a02b9c590f38.png)

**Comment by fabiomaffioletti** [comment]
See discussion here: https://github.com/fabiomaffioletti/jsondoc/issues/70

**Comment by MarcMielke** [comment]
hmm - what then are the semantics of the 'required' in "@ApiPathParam(required = false, name = "id"...." ?

**Comment by fabiomaffioletti** [comment]
This is a mistake. I'll remove the "required" property from the ApiPathParam annotation. Thank you.
