### ISSUE TITLE
Support including Body/Response objects as Api Objects

### ISSUE THREAD

**Issue by matt-blanchette** [fabiomaffioletti/jsondoc#87]
Currently Body/Response objects annotated with @ApiBodyObject/@ApiResponseObject are given a type name in the Body/Response object.
These Body/Response objects will only show up in the Objects section if they are annotated with @ApiObject (and will be empty unless also annotated with @ApiObjectField).

It would be nice to support these existing types as Api Objects, even if not annotated with @ApiObject/@ApiObjectField (basic POJOs).

One partial workaround I found was creating a new type annotated with @ApiObject(show = false),
then including inner classes extending existing types and adding @ApiObject annotation.
This includes the object type names but without any fields.
Maybe an option on @ApiObject to include all fields by default 
or specify a list of field names to include?

Support could also be added for Jackson annotated types (especially for Spring MVC), handling these as @ApiObject/@ApiObjectField.

For the UI, ideally there would be a link from Body/Response object types to the Object definition.

**Comment by fabiomaffioletti** [comment]
JSONDoc is based on an opt-in mechanism. If you want to document something, then you need to explicitly say it by putting an annotation. This answers also: "Maybe an option on @ApiObject to include all fields by default or specify a list of field names to include?" If you don't want a field to be documented, just don't put the annotation on it.

Regarding the UI, your suggestion would be a good improvement, please open a specific issue on that, but consider that this will have low priority.

**Comment by matt-blanchette** [comment]
Ok, agreed, I'll add the new UI issue.
