### ISSUE TITLE
Sort api methods by path

### ISSUE THREAD

**Issue by matt-blanchette** [fabiomaffioletti/jsondoc#88]
On rebuilding doc json, the api methods are reordered.
Ideally these would be sorted by path, for consistency after rebuilding.

I added the following sort in ui html to work around it:

```javascript
$.each(data.apis, function(i, groupApis) {
        $.each(groupApis, function(j, api) {
            api.methods.sort(function(a,b){
                return a.path.localeCompare(b.path);
            });
        });
    });
```

**Comment by fabiomaffioletti** [comment]
This needs to be done server side. BTW good idea. I'll do that.
