### ISSUE TITLE
@ApiMethod annotation exception

### ISSUE THREAD

**Issue by dpasic** [fabiomaffioletti/jsondoc#91]
We are using Web application with Spring framework on Tomcat 7 server and using JSONDoc version 1.1.5 (jsondoc-ui-webjar). We put @ApiMethod annotation on test method as shown here http://pastebin.com/3Qkc5x5P and while generating jsondoc exception was thrown as shown here http://pastebin.com/z4RGQ8tm

If we try to use @ApiMethod annotation on method which is not marked with Spring annotation it works well.

**Comment by fabiomaffioletti** [comment]
Please upgrade to the latest version of JSONDoc: the exception you reported is fixed. And make sure that if you want to document the response object you also add @ApiResponseObject annotation.

**Comment by dpasic** [comment]
Thanks for tip, it works fine now with 1.1.8 version of JSONDoc.

**Comment by fabiomaffioletti** [comment]
Great!
