### ISSUE TITLE
java.lang.NoSuchMethodError on includePackage

### ISSUE THREAD

**Issue by aurbano** [fabiomaffioletti/jsondoc#94]
I might be missing something, but I keep getting the following error:

```
java.lang.NoSuchMethodError: org.reflections.util.FilterBuilder.includePackage([Ljava/lang/String;)Lorg/reflections/util/FilterBuilder;
```

I've already tried all possible combinations of the package name, with no luck. Any ideas?

I'm using reflections 0.9.9.RC2, if you need any other library version to debug let me know

**Comment by fabiomaffioletti** [comment]
You need to use version 0.9.9.

**Comment by aurbano** [comment]
Brilliant, thank you so much!
